import { StyleSheet, Platform, StatusBar } from 'react-native';

const getStyles = (theme: any) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  header: { paddingTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight, paddingHorizontal: 16, paddingBottom: 16 },
  headerContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  userInfo: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 12 },
  avatarContainer: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'rgba(255,255,255,0.3)' },
  avatarText: { fontSize: 18, fontWeight: '600', color: 'white' },
  userDetails: { marginLeft: 12 },
  userName: { fontSize: 18, fontWeight: '600', color: 'white' },
  userStatus: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  content: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: theme.background },
  messageList: { padding: 16, paddingBottom: 20 },
  messageContainer: { marginVertical: 6, maxWidth: '85%', flexDirection: 'row', alignItems: 'flex-end' },
  ownMessage: { alignSelf: 'flex-end', marginLeft: 60 },
  otherMessage: { alignSelf: 'flex-start', marginRight: 60 },
  otherAvatarContainer: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.surfaceSecondary, justifyContent: 'center', alignItems: 'center', marginRight: 8, marginBottom: 4 },
  otherAvatarText: { fontSize: 14, fontWeight: '600', color: theme.text },
  messageBubble: { padding: 14, borderRadius: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },
  ownBubble: { backgroundColor: theme.primary, borderBottomRightRadius: 4 },
  otherBubble: { backgroundColor: theme.surface, borderBottomLeftRadius: 4, borderWidth: 1, borderColor: theme.border },
  messageText: { fontSize: 16, lineHeight: 22, marginBottom: 6 },
  ownMessageText: { color: theme.surface },
  otherMessageText: { color: theme.text },
  messageTime: { fontSize: 11, fontWeight: '500' },
  ownMessageTime: { color: 'rgba(255,255,255,0.7)', alignSelf: 'flex-end' },
  otherMessageTime: { color: theme.textSecondary, alignSelf: 'flex-end' },
  inputContainer: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: 16, paddingVertical: 12, backgroundColor: theme.surface, borderTopWidth: 1, borderTopColor: theme.border, paddingBottom: Platform.OS === 'ios' ? 34 : 12 },
  inputWrapper: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', backgroundColor: theme.surfaceSecondary, borderRadius: 25, paddingHorizontal: 16, paddingVertical: 8, marginRight: 12, borderWidth: 1, borderColor: theme.border },
  attachButton: { marginRight: 8, padding: 4 },
  input: { flex: 1, fontSize: 16, maxHeight: 100, color: theme.text, paddingVertical: 4 },
  splitBillButton: { marginLeft: 8, padding: 4 },
  sendButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: theme.primary, justifyContent: 'center', alignItems: 'center', shadowColor: theme.primary, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 4 },
  sendButtonDisabled: { backgroundColor: theme.surfaceSecondary, shadowOpacity: 0, elevation: 0 },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
  emptyIconContainer: { width: 120, height: 120, borderRadius: 60, backgroundColor: theme.surfaceSecondary, justifyContent: 'center', alignItems: 'center', marginBottom: 24, borderWidth: 2, borderColor: theme.border },
  emptyText: { fontSize: 20, fontWeight: '600', color: theme.text, marginBottom: 8, textAlign: 'center' },
  emptySubtext: { fontSize: 16, color: theme.textSecondary, textAlign: 'center', lineHeight: 22 },
  modalContainer: { flex: 1 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16 },
  modalCloseButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: 'white' },
  modalSaveButton: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 20 },
  modalSaveText: { fontSize: 16, fontWeight: '600', color: 'white' },
  modalContent: { flex: 1, padding: 20 },
  modalCard: { backgroundColor: theme.surface, borderRadius: 20, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 8 },
  inputGroup: { marginBottom: 24 },
  inputLabel: { fontSize: 16, fontWeight: '600', color: theme.text, marginBottom: 8 },
  textInput: { backgroundColor: theme.surfaceSecondary, borderRadius: 12, padding: 16, fontSize: 16, borderWidth: 1, borderColor: theme.border, color: theme.text },
  amountInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.surfaceSecondary, borderRadius: 12, borderWidth: 1, borderColor: theme.border },
  currencySymbol: { fontSize: 18, fontWeight: '600', color: theme.primary, paddingLeft: 16, paddingRight: 8 },
  amountInput: { flex: 1, padding: 16, fontSize: 20, fontWeight: 'bold', color: theme.text },
  splitPreview: { backgroundColor: theme.surfaceSecondary, padding: 20, borderRadius: 16, borderWidth: 1, borderColor: theme.border },
  previewHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  previewTitle: { fontSize: 18, fontWeight: '600', color: theme.text, marginLeft: 8 },
  previewContent: { gap: 12 },
  previewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  previewLabel: { fontSize: 14, color: theme.textSecondary },
  previewValue: { fontSize: 16, fontWeight: '600', color: theme.text },
  searchHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, backgroundColor: theme.surface, borderBottomWidth: 1, borderBottomColor: theme.border },
  searchBackButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.surfaceSecondary, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  searchInput: { flex: 1, height: 40, borderRadius: 20, paddingHorizontal: 16, fontSize: 16, borderWidth: 1 },
  searchResultsList: { padding: 16 },
  searchResultItem: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 12, borderWidth: 1, marginBottom: 8 },
  searchResultContent: { flex: 1 },
  searchResultText: { fontSize: 16, lineHeight: 22, marginBottom: 4 },
  searchResultTime: { fontSize: 12 },
  searchEmptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
  searchEmptyText: { fontSize: 16, textAlign: 'center', marginTop: 16 },
  splitBillContainer: { padding: 12 },
  splitBillHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  splitBillTitle: { fontSize: 16, fontWeight: '600', marginLeft: 6 },
  splitBillDescription: { fontSize: 14, marginBottom: 12, lineHeight: 20 },
  splitBillDetails: { marginBottom: 12 },
  splitBillRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  splitBillLabel: { fontSize: 14 },
  splitBillValue: { fontSize: 14, fontWeight: '600' },
  paidText: { fontSize: 12, fontWeight: '600' },
  splitBillActions: { flexDirection: 'row', gap: 8 },
  payButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 6, alignItems: 'center' },
  payButtonText: { fontSize: 14, fontWeight: '600' },
  remindButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 6, borderWidth: 1, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 4 },
  remindButtonText: { fontSize: 14, fontWeight: '600' },
  settledContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 8, gap: 4 },
  settledText: { fontSize: 14, fontWeight: '600' },
  mediaContainer: { marginBottom: 8, borderRadius: 12, overflow: 'hidden' },
  mediaImage: { width: 200, height: 200, borderRadius: 12 },
  videoPlaceholder: { width: 200, height: 120, backgroundColor: theme.surfaceSecondary, borderRadius: 12, justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  audioPlaceholder: { flexDirection: 'row', alignItems: 'center', padding: 12, backgroundColor: theme.surfaceSecondary, borderRadius: 12, minWidth: 200 },
  audioInfo: { flex: 1, marginLeft: 12 },
  documentPlaceholder: { flexDirection: 'row', alignItems: 'center', padding: 12, backgroundColor: theme.surfaceSecondary, borderRadius: 12, minWidth: 200 },
  documentInfo: { flex: 1, marginLeft: 12 },
  mediaText: { fontSize: 16, fontWeight: '600', marginTop: 4 },
  mediaDuration: { fontSize: 12, marginTop: 2 },
  mediaSize: { fontSize: 12, marginTop: 2 },
  mediaCaption: { marginTop: 6 },
  videoContainer: { position: 'relative' },
  playButton: { position: 'absolute', top: '50%', left: '50%', transform: [{ translateX: -20 }, { translateY: -20 }], width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0, 0, 0, 0.7)', justifyContent: 'center', alignItems: 'center' },
  playButtonText: { fontSize: 16, color: 'white' },
  imageErrorPlaceholder: { backgroundColor: theme.surfaceSecondary, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: theme.border, borderStyle: 'dashed' },
  retryButton: { marginTop: 8, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: theme.surface, borderRadius: 16, borderWidth: 1, borderColor: theme.primary },
  retryText: { fontSize: 12, fontWeight: '600' },
});

export default getStyles;
